# YAML for setting up a conda environment for
# the exploits library
name: exploits
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - pandas
  - pip
  - pylint
  - python>=3.9
  - pytest
  - pyfiglet
  - pygments
  - seaborn
